version: "3.9"
services:
  opcserver:
    build:
      context: ./opcserver
    ports:
      - "4840:4840"
    network_mode: "host"
  modbusserver:
    build:
      context: ./modbusserver
    ports:
      - "502:502"
    network_mode: "host"