version: "3.9"
services:
  opcserver:
    build:
      context: ./opcserver
    ports:
      - "4840:4840"
    network_mode: "host"
    restart: always
  modbusserver:
    build:
      context: ./modbusserver
    ports:
      - "502:502"
    network_mode: "host"
    restart: always
gateway:
    build:
      context: ./gateway
      args:
        OPC_UA_GATEWAY_VERSION: 1014.0.213
    environment:
    - baseUrl=https://felix.eu-latest.cumulocity.com
    - tenantId=t682538178
    - gatewayIdentifier=opcua-revpi
    - gatewayName=OPCUA-Gateway
    volumes:
    - ./data/:/data
    restart: always
